"""Generate server-readable, dependency-free portfolio pages."""
from pathlib import Path
from html import escape as esc
import json
ROOT=Path(__file__).resolve().parent
OUT=ROOT/'dist'
BASE='https://www.usmanov.biz'
D={
'ru':dict(name='Ануар Усманов',title='Ануар Усманов — IT-инфраструктура, CRM и digital-маркетинг',description='Администрирование IT-инфраструктуры, внедрение CRM и автоматизация бизнеса, digital-маркетинг и сквозная аналитика. Ануар Усманов — опыт в IT с 2008 года.',intro=['Эксперт по IT-инфраструктуре и автоматизации бизнеса.','Помогаю компаниям расти через digital-маркетинг и аналитику.'],available='Открыт для новых проектов',contact='Связаться',resume='Резюме',tabs=['Чем могу быть полезен','Опыт работы','Интересы'],services=['Проектирование и администрирование IT-инфраструктуры.','Внедрение CRM-систем и автоматизация процессов.','Управление digital-маркетингом и сквозной аналитикой.'],experience=[['IT-инфраструктура','В IT с 2008 года. Администрировал более 1000 устройств. Настраиваю серверы, сети, Active Directory, VPN, резервное копирование и безопасность.','Windows Server · Linux · MikroTik · Microsoft 365'],['CRM и автоматизация','Внедряю amoCRM, Bitrix24 и Kommo. Интегрирую сервисы, настраиваю мониторинг и поддержку пользователей. Готовлю документацию и инструкции для команд.','amoCRM · Bitrix24 · Kommo · Zabbix · Grafana'],['Маркетинг и аналитика','Реклама в Google Ads, Яндекс Директе, VK Ads и Meta Ads. Сквозная аналитика, GA4, Метрика, GTM и Conversion API. SEO, ретаргетинг и A/B-тесты.','Google Ads · Яндекс Директ · GA4 · GTM · SEO']],interests=[['Веб-разработка и ИИ','Создаю сайты и дашборды с помощью ИИ. Применяю специализированные skills, адаптирую интерфейсы под разные экраны и развёртываю проекты на Vercel.','Сайты · Дашборды · AI · Vercel'],['За пределами экрана','Люблю пешие маршруты в горах, настольный теннис и пляжный волейбол. Есть спортивный разряд по настольному теннису.','Горы · Теннис · Волейбол'],['Образование и языки','ЕНУ им. Л. Н. Гумилёва, математическое компьютерное моделирование, 2009. Казахский — родной, русский — C2, турецкий — B2, английский — B1.','Windows Server · Веб-разработка · Vue.js']],close='Закрыть',prev='Назад',next='Далее',skip='Перейти к содержимому',lang='Язык сайта',contactTitle='Обсудим вашу задачу',contactText='Напишите о проекте, задачах и сроках — обсудим, чем я могу помочь.',resumeTitle='Опыт в деталях',resumeText='Выберите направление. Резюме на русском языке.',pdf=['Системный администратор','Трафик-менеджер'],dates=['Февраль 2025 · PDF','Март 2025 · PDF']),
'en':dict(name='Anuar Usmanov',title='Anuar Usmanov — IT infrastructure, CRM & digital marketing',description='IT infrastructure administration, CRM implementation, business automation, digital marketing and end-to-end analytics. Anuar Usmanov — working in IT since 2008.',intro=['IT infrastructure and business automation specialist.','Helping companies grow through digital marketing and analytics.'],available='Available for new projects',contact='Get in touch',resume='Résumé',tabs=['How I can help','Experience','Interests'],services=['IT infrastructure design and administration.','CRM implementation and business process automation.','Digital marketing and end-to-end analytics.'],experience=[['IT infrastructure','Working in IT since 2008. Managed corporate infrastructure with more than 1,000 devices. I configure Windows Server, Active Directory, DNS, DHCP, VPN, backups and security policies.','Windows Server · Linux · MikroTik · Microsoft 365'],['CRM & automation','I implement and maintain amoCRM, Bitrix24 and Kommo. I connect internal systems with external services, set up monitoring and user support, and create documentation and team instructions.','amoCRM · Bitrix24 · Kommo · Zabbix · Grafana'],['Marketing & analytics','I launch Google Ads, Yandex Direct, VK Ads and Meta Ads campaigns. I configure GA4, Yandex Metrica, GTM and Conversion API, and work on SEO, landing pages, retargeting and A/B tests.','Google Ads · Yandex Direct · GA4 · GTM · SEO']],interests=[['Web development & AI','I build websites and dashboards with AI, using specialized skills, adapting interfaces to different screens and deploying projects on Vercel.','Websites · Dashboards · AI · Vercel'],['Beyond the screen','I enjoy mountain hiking, table tennis and beach volleyball. I hold a competitive rank in table tennis.','Mountains · Table tennis · Volleyball'],['Education & languages','L. N. Gumilyov Eurasian National University, mathematical computer modelling, 2009. Kazakh — native, Russian — C2, Turkish — B2, English — B1.','Windows Server · Web development · Vue.js']],close='Close',prev='Previous',next='Next',skip='Skip to content',lang='Site language',contactTitle='Let’s discuss your project',contactText='Tell me about your project, goals and timeline — we can explore how I can help.',resumeTitle='Experience in detail',resumeText='Choose a field. Both résumés are in Russian.',pdf=['System administrator','Traffic manager'],dates=['February 2025 · PDF','March 2025 · PDF']),
'tr':dict(name='Anuar Usmanov',title='Anuar Usmanov — BT altyapısı, CRM ve dijital pazarlama',description='BT altyapı yönetimi, CRM kurulumu, iş süreçleri otomasyonu, dijital pazarlama ve uçtan uca analiz. Anuar Usmanov — 2008’den beri BT deneyimi.',intro=['BT altyapısı ve iş süreçleri otomasyonu uzmanı.','Dijital pazarlama ve analizle şirketlerin büyümesine yardımcı oluyorum.'],available='Yeni projelere açığım',contact='İletişime geçin',resume='Özgeçmiş',tabs=['Nasıl yardımcı olabilirim','Deneyim','İlgi alanları'],services=['BT altyapısı tasarımı ve yönetimi.','CRM kurulumu ve iş süreçleri otomasyonu.','Dijital pazarlama ve uçtan uca analiz.'],experience=[['BT altyapısı','2008’den beri BT alanında çalışıyorum. 1.000’den fazla cihazdan oluşan kurumsal altyapıyı yönettim. Windows Server, Active Directory, DNS, DHCP, VPN, yedekleme ve güvenlik politikalarını yapılandırıyorum.','Windows Server · Linux · MikroTik · Microsoft 365'],['CRM ve otomasyon','amoCRM, Bitrix24 ve Kommo kurulumu ve desteği sağlıyorum. İç sistemleri dış hizmetlerle entegre ediyor, izleme ve kullanıcı desteğini kuruyor, ekipler için belgeler ve talimatlar hazırlıyorum.','amoCRM · Bitrix24 · Kommo · Zabbix · Grafana'],['Pazarlama ve analiz','Google Ads, Yandex Direct, VK Ads ve Meta Ads kampanyalarını yönetiyorum. GA4, Yandex Metrica, GTM ve Conversion API kurulumu yapıyorum. SEO, açılış sayfaları ve A/B testleriyle çalışıyorum.','Google Ads · Yandex Direct · GA4 · GTM · SEO']],interests=[['Web geliştirme ve yapay zekâ','Yapay zekâ ve özel skills kullanarak web siteleri ve panolar geliştiriyorum. Arayüzleri farklı ekranlara uyarlıyor, projeleri Vercel’de yayımlıyorum.','Web siteleri · Panolar · AI · Vercel'],['Ekranın dışında','Dağ yürüyüşlerini, masa tenisini ve plaj voleybolunu seviyorum. Masa tenisinde spor derecem var.','Dağlar · Masa tenisi · Voleybol'],['Eğitim ve diller','L. N. Gumilyov Avrasya Milli Üniversitesi, matematiksel bilgisayar modellemesi, 2009. Kazakça — ana dil, Rusça — C2, Türkçe — B2, İngilizce — B1.','Windows Server · Web geliştirme · Vue.js']],close='Kapat',prev='Önceki',next='Sonraki',skip='İçeriğe geç',lang='Site dili',contactTitle='Projenizi konuşalım',contactText='Projenizi, hedeflerinizi ve takviminizi anlatın; nasıl yardımcı olabileceğimi konuşalım.',resumeTitle='Ayrıntılı deneyim',resumeText='Bir alan seçin. Özgeçmişler Rusçadır.',pdf=['Sistem yöneticisi','Trafik yöneticisi'],dates=['Şubat 2025 · PDF','Mart 2025 · PDF'])}
SOCIAL={'WhatsApp':'https://wa.me/905541892668','Telegram':'https://t.me/anuar_usm','Instagram':'https://www.instagram.com/anuar.usmanov','Facebook':'https://www.facebook.com/anuar.usmanov.71'}
ICONS={'WhatsApp':'<path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0012.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 005.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.821 11.821 0 00-3.48-8.413Z"/>','Telegram':'<path d="m21 3-4 18-6-5-4 3 1-6L21 3ZM8 13l9-6-6 9M3 10l18-7"/>','Instagram':'<rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r=".6"/>','Facebook':'<path d="M14 21v-8h3l.5-4H14V7c0-1 .5-2 2-2h2V2h-3c-3 0-5 2-5 5v2H7v4h3v8"/>'}
def route(l): return '/' if l=='ru' else f'/{l}/'
for lang,d in D.items():
 canonical=BASE+route(lang)
 alternates=''.join(f'<link rel="alternate" hreflang="{l}" href="{BASE}{route(l)}">' for l in D)+f'<link rel="alternate" hreflang="x-default" href="{BASE}/">'
 schema={'@context':'https://schema.org','@graph':[{'@type':'Person','@id':BASE+'/#person','name':'Ануар Усманов','alternateName':'Anuar Usmanov','url':BASE+'/','image':BASE+'/assets/portrait.webp','email':'rest.vip7@gmail.com','sameAs':list(SOCIAL.values()),'knowsAbout':['IT infrastructure','CRM','Business automation','Digital marketing','Web analytics']},{'@type':'WebSite','@id':BASE+'/#website','url':BASE+'/','name':'Anuar Usmanov','inLanguage':list(D)},{'@type':'ProfilePage','@id':canonical+'#webpage','url':canonical,'name':d['title'],'description':d['description'],'inLanguage':lang,'mainEntity':{'@id':BASE+'/#person'},'isPartOf':{'@id':BASE+'/#website'}}]}
 socials=''.join(f'<a href="{u}" target="_blank" rel="noopener noreferrer" aria-label="{n}" title="{n}"><svg viewBox="0 0 24 24" aria-hidden="true">{ICONS[n]}</svg></a>' for n,u in SOCIAL.items())
 langs=''.join(f'<a href="{route(l)}" lang="{l}" hreflang="{l}"'+(' aria-current="page"' if l==lang else '')+f'>{label}</a>' for l,label in [('ru','Русский'),('en','English'),('tr','Türkçe')])
 tabs=''.join(f'<a id="tab-{key}" class="tab" href="#{key}"'+(' aria-current="true"' if i==0 else '')+f'>{label}</a>' for i,(key,label) in enumerate(zip(['services','experience','interests'],d['tabs'])))
 services=''.join(f'<a class="service-row" href="#experience-{i}"><span class="number">0{i+1}</span><span>{label}</span><span class="arrow" aria-hidden="true">→</span></a>' for i,label in enumerate(d['services']))
 panels=''
 for key in ['experience','interests']:
  cards=''.join(f'<article class="detail" id="{key}-{i}" aria-labelledby="heading-{key}-{i}"><span class="detail-index">0{i+1} / 03</span><h3 id="heading-{key}-{i}">{esc(title)}</h3><p>{esc(body)}</p><p class="tags">{esc(tags)}</p></article>' for i,(title,body,tags) in enumerate(d[key]))
  pager=''.join(f'<button type="button" class="page-dot" data-page="{i}" aria-label="{esc(title)}" aria-pressed="{str(i==0).lower()}">0{i+1}</button>' for i,(title,_,_) in enumerate(d[key]))
  panels+=f'<section id="{key}" class="panel" aria-labelledby="tab-{key}"><h2 class="sr-only">{d["tabs"][1 if key=="experience" else 2]}</h2><div class="detail-stack">{cards}</div><div class="pager"><button type="button" data-step="-1" aria-label="{d["prev"]}">←</button><div class="page-dots">{pager}</div><button type="button" data-step="1" aria-label="{d["next"]}">→</button></div></section>'
 pdf=''.join(f'<a class="dialog-link" href="/assets/anuar-usmanov-{kind}.pdf" download><span>{d["pdf"][i]}<small>{d["dates"][i]}</small></span>↓</a>' for i,kind in enumerate(['it','digital']))
 html=f'''<!doctype html><html lang="{lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>{esc(d['title'])}</title><meta name="description" content="{esc(d['description'])}"><meta name="robots" content="index,follow,max-image-preview:large"><meta name="theme-color" content="#131414"><meta name="color-scheme" content="dark"><link rel="canonical" href="{canonical}">{alternates}<meta property="og:type" content="profile"><meta property="og:site_name" content="Anuar Usmanov"><meta property="og:title" content="{esc(d['title'])}"><meta property="og:description" content="{esc(d['description'])}"><meta property="og:url" content="{canonical}"><meta property="og:locale" content="{dict(ru='ru_RU',en='en_US',tr='tr_TR')[lang]}"><meta name="twitter:card" content="summary"><meta name="twitter:title" content="{esc(d['title'])}"><meta name="twitter:description" content="{esc(d['description'])}"><link rel="icon" href="/assets/favicon.svg" type="image/svg+xml"><link rel="preload" href="/assets/portrait.webp" as="image"><link rel="stylesheet" href="/style.css"><script src="/app.js" defer></script><script type="application/ld+json">{json.dumps(schema,ensure_ascii=False)}</script></head>
<body><a class="skip" href="#content">{d['skip']}</a><div class="site"><header class="hero"><details class="language"><summary aria-label="{d['lang']}">{lang.upper()}<svg viewBox="0 0 16 16" aria-hidden="true"><path d="m4 6 4 4 4-4"/></svg></summary><nav aria-label="{d['lang']}">{langs}</nav></details><div class="hero-copy"><h1>{d['name']}</h1><div class="intro"><p>{d['intro'][0]}</p><p>{d['intro'][1]}</p></div><nav class="socials" aria-label="Social">{socials}</nav></div><div class="portrait"><img src="/assets/portrait.webp" alt="{d['name']}" width="1254" height="1254" fetchpriority="high" decoding="async"></div><div class="hero-bottom"><p class="availability"><span aria-hidden="true"></span>{d['available']}</p><div class="actions"><a class="primary" href="https://t.me/anuar_usm" data-dialog="contact">{d['contact']} <span aria-hidden="true">↗</span></a><a class="resume-link" href="/assets/anuar-usmanov-it.pdf" data-dialog="resume">{d['resume']} <span aria-hidden="true">↓</span></a></div></div></header>
<main id="content" tabindex="-1"><nav class="tabs" aria-label="{d['tabs'][1]}">{tabs}</nav><div class="panels"><section id="services" class="panel" aria-labelledby="tab-services"><h2 class="sr-only">{d['tabs'][0]}</h2><div class="services">{services}</div></section>{panels}</div></main><footer><span>© 2026 {d['name']}</span><div><a href="https://t.me/anuar_usm" target="_blank" rel="noopener noreferrer">Telegram ↗</a><a href="mailto:rest.vip7@gmail.com">Email ↗</a></div></footer></div>
<dialog id="contact" aria-labelledby="contact-title"><button class="close" aria-label="{d['close']}">×</button><h2 id="contact-title">{d['contactTitle']}</h2><p>{d['contactText']}</p><a class="dialog-link" href="https://t.me/anuar_usm" target="_blank" rel="noopener noreferrer"><span>Telegram<small>@anuar_usm</small></span>↗</a><a class="dialog-link" href="https://wa.me/905541892668" target="_blank" rel="noopener noreferrer"><span>WhatsApp<small>+90 554 189 26 68</small></span>↗</a><a class="dialog-link" href="mailto:rest.vip7@gmail.com"><span>Email<small>rest.vip7@gmail.com</small></span>↗</a></dialog><dialog id="resume" aria-labelledby="resume-title"><button class="close" aria-label="{d['close']}">×</button><h2 id="resume-title">{d['resumeTitle']}</h2><p>{d['resumeText']}</p>{pdf}</dialog></body></html>'''
 directory=OUT if lang=='ru' else OUT/lang
 directory.mkdir(parents=True,exist_ok=True)
 (directory/'index.html').write_text(html,encoding='utf-8')
(OUT/'robots.txt').write_text('User-agent: *\nAllow: /\n\nSitemap: '+BASE+'/sitemap.xml\n',encoding='utf-8')
urls=''.join('<url><loc>'+BASE+route(lang)+'</loc>'+''.join(f'<xhtml:link rel="alternate" hreflang="{l}" href="{BASE}{route(l)}"/>' for l in D)+f'<xhtml:link rel="alternate" hreflang="x-default" href="{BASE}/"/></url>' for lang in D)
(OUT/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">'+urls+'</urlset>',encoding='utf-8')
(OUT/'404.html').write_text('<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex"><title>Страница не найдена — Ануар Усманов</title><link rel="stylesheet" href="/style.css"></head><body><main class="not-found"><p>404</p><h1>Страница не найдена</h1><a class="primary" href="/">На главную ↗</a></main></body></html>',encoding='utf-8')
print('Built RU, EN, TR pages, sitemap, robots and 404.')
